volumes:
    postgres_db:
        driver: local
        name: shopping_postgres_db

services:
    python:
        container_name: shopping
        build:
            context: .
        ports:
            - 8000:8000
        env_file:
            - ./.env
        depends_on:
            - postgres
        restart: always

    postgres:
        image: postgres:16.4
        environment:
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_DATABASE}
        volumes:
            - postgres_db:/var/lib/postgresql/data
