services:
    proxy:
        image: nginx:1.26
        volumes:
            - ./docker/nginx/nginx.${ENVIRONMENT}.conf:/etc/nginx/conf.d/site.conf
        ports:
            - 80:80
        depends_on:
            - python

    python:
        command: uv run uvicorn --factory main:create_app --host 0.0.0.0 --reload --timeout-keep-alive 600
        volumes:
            - ./src:/app/src
        stdin_open: true
        tty: true

    postgres:
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=test123
        volumes:
            - ./docker/postgresql:/docker-entrypoint-initdb.d
