#!/bin/bash

container=$1
valid_containers=("mysql" "api" "proxy")
valid=0
for valid_container in ${valid_containers[@]}; do
	if [[ $container == $valid_container ]]; then
		valid=1
		break
	fi
done
if [[ $valid == 0 ]]; then
	echo "No valid container: mysql api proxy"
	exit 1
fi

shell="bash"
if [[ $container == "api" ]]; then
	shell="ash"
fi

docker exec -it shopping-$container $shell
