"""Add purchase amount

Revision ID: 7f3afa6964f1
Revises: 9c3b1e040740
Create Date: 2025-05-16 17:49:30.857013

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f3afa6964f1"
down_revision: Union[str, None] = "9c3b1e040740"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("purchases", sa.Column("amount", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("purchases", "amount")
    # ### end Alembic commands ###
